version: '3.5'
# 网络配置
networks:
  backend:
    name:  backend
    external: true
    driver: ${NETWORKS_DRIVER}
    ipam:
      config:
        - subnet: 172.20.0.0/16

# 服务容器配置
services:
  #bbs 服务,提供restapi服务
  golemmy:                                # 自定义容器名称
    build:
      context: ./golemmy                  # 指定构建使用的 Dockerfile 文件
    container_name: golemmy
    environment:                         # 设置环境变量
      - TZ=${TZ}
    privileged: true
    volumes:                             # 设置挂载目录
      - ${APPS_PATH_HOST}/golemmy:/app  # 引用 .env 配置中 APPS_PATH_HOST 变量，将宿主机上app及配置存放的目录挂载到容器中/app目录
      - ${DATA_PATH_HOST}/golemmy:/static  # 引用 .env 配置中 DATA_PATH_HOST 变量，将宿主机上data存放的目录挂载到容器中/static 目录
    ports:                               # 设置端口映射
      - "${HTTPSERVER_PORT}:18888"
    networks:
      - backend
    restart: always                      # 指定容器退出后的重启策略为始终重启



  #推送服务
  wspush:
    build:
      context: ./wspush
    container_name: wspush
    user: root
    privileged: true

    volumes:
      - ${APPS_PATH_HOST}/wspush:/app
    ports:
    - "${WSSERVER_PORT}:28888"
    networks:
      - backend
    restart: always

