version: "3.5"
services:
  nats:
    image: nats
    container_name: nats
    ports:
      - "8222:8222"
      - "4222:4222"
    command: "--cluster_name NATS --cluster nats://0.0.0.0:6222 --http_port 8222 "
    networks: ["nats"]
  nats-1:
    image: nats
    container_name: nats-1
    ports:
      - "18222:8222"
      - "14222:4222"
    command: "--cluster_name NATS --cluster nats://0.0.0.0:6222 --routes=nats://ruser:T0pS3cr3t@nats:6222"
    networks: ["nats"]
    depends_on: ["nats"]
  nats-2:
    image: nats
    container_name: nats-2
    ports:
      - "28222:8222"
      - "24222:4222"
    command: "--cluster_name NATS --cluster nats://0.0.0.0:6222 --routes=nats://ruser:T0pS3cr3t@nats:6222"
    networks: ["nats"]
    depends_on: ["nats"]
  nats-ui:
    container_name: natsui
    image: sphqxe/nats-webui:latest
    networks: ["nats"]
    ports:
      - "5222:80"

networks:
  nats:
    name: nats